# Generated by Django 3.2.7 on 2021-10-24 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date_of_publication', models.DateField(auto_now_add=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('auto_brand', models.CharField(max_length=20)),
                ('auto_model', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=30)),
                ('condition', models.TextField()),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPhoto',
            fields=[
                ('id_client_photo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCar',
            fields=[
                ('id_client_car', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('id_car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
                ('id_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id_car_photo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
