# Generated by Django 3.2.7 on 2021-10-31 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_clientphoto_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carphoto',
            name='id_client',
        ),
        migrations.AddField(
            model_name='carphoto',
            name='id_car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.car'),
            preserve_default=False,
        ),
    ]
