# Generated by Django 3.2.7 on 2021-10-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211031_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ImageField(default='', upload_to='car_img/'),
            preserve_default=False,
        ),
    ]
