# Generated by Django 3.2.7 on 2021-11-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_car_car_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarPhoto',
        ),
    ]
