# Generated by Django 3.2.7 on 2021-11-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_considerations'),
    ]

    operations = [
        migrations.AddField(
            model_name='considerations',
            name='client_phone_number',
            field=models.IntegerField(default='89041523161'),
            preserve_default=False,
        ),
    ]
