# Generated by Django 3.2.7 on 2021-11-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_considerations_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='considerations',
            name='status',
            field=models.CharField(default='На рассмотрении', max_length=56),
        ),
    ]
