# Generated by Django 3.2.7 on 2021-11-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211121_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='day_price',
            field=models.IntegerField(default=1000),
        ),
    ]
