# Generated by Django 3.2.7 on 2021-11-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_car_day_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='day_price',
            field=models.IntegerField(),
        ),
    ]
